---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 12.20.3

verifier:
  name: inspec

platforms:
  # - name: ubuntu-16.04
  # - name: centos-7.3
  # - name: windows-2012r2
  - name: mwrock/Windows2016
    os_type: windows
    transport:
      name: winrm
      elevated: true
suites:
  - name: default
    run_list:
      - recipe[demo_base_linux::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
